### ISSUE TITLE
block forks the chain at height,but does not cause a reorganize

### ISSUE THREAD

**Issue by hzhb908** [massnetorg/MassNet-miner#19]
![微信图片_20210726163134](https://user-images.githubusercontent.com/82793477/126958690-6ed59178-b172-4e82-81dc-ba50c406b5a1.png)

**Comment by aquabubble** [comment]
This is normal

**Comment by miguelcarv1973** [comment]
do you have errors ...udp connection, peers connection, shareauthsignature failed....etc..., only happens after binding_count is >0
