### ISSUE TITLE
massminercli configureminer 50 ms1q....  error500.. how to fix?

### ISSUE THREAD

**Issue by wangxinyu2018** [massnetorg/MassNet-miner#28]
INFO[2021-07-29T17:26:18+08:00] using config file                             file=config.go func=cmd.logBasicInfo line=68 tid=1
INFO[2021-07-29T17:26:18+08:00] configure-miner called                        capacity=50 coinbase_addresses="ms1qq9gtqw02dx0nk3hg6d83quqdh3ru00wugjjkesny2cqfdlddtzy0q8tnul6" file=miner.go func=cmd.glob..func17 line=49 tid=1
ERRO[2021-07-29T17:26:18+08:00] fail on request with code                     code=500 f7="{util.go,cmd.(*httpServer).call,68}" f8="{util.go,cmd.(*Client).CallRaw,102}" f9="{util.go,cmd.(*Client).Call,107}" tid=1
{
  "capacity": "0",
  "payoutAddresses": [
  ],
  "passphrase": ""
}

**Comment by wangxinyu2018** [comment]
how to fix?

**Comment by wangxinyu2018** [comment]
how to fix ? help ! thanks

**Comment by hzhb908** [comment]
不用理会，这是你矿机高度没同步完成，massminer那个窗口运行一天左右，同步完成了再执行这个命令就没问题了

**Comment by wangxinyu2018** [comment]
> 不用理会，这是你矿机高度没同步完成，massminer那个窗口运行一天左右，同步完成了再执行这个命令就没问题了

同步完成了，这是请求报500错误，命令行提示输入2个参数，实际内部逻辑需要三个参数。
