### ISSUE TITLE
warn

### ISSUE THREAD

**Issue by hzhb908** [massnetorg/MassNet-miner#33]
WARN[2021-08-02T17:02:58+08:00] coinbase associated with pool pk not in list  coinbase=580c5f5f260e3ea957b506a9dd46c12d16321ba3fc51f6f48187fec2483b5d1f file=template.go func=blockchain.newBlockTemplate.func3 line=690 poolPk=XXXXXXXXX  tid=551

**Comment by panyang1217** [comment]
same issue after binding to a pool. do you fix it?
